import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Outfit } from "next/font/google";

export const metadata: Metadata = {
  title: "Towner Admin",
  description: "Generated by Towner Admin",
};

const outfit = Outfit({ subsets: ["latin"] });


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${outfit.className} bg-gray-100`}
        >
          {children}
        </body>
      </html>
    </ClerkProvider>

  );
}
